### ISSUE TITLE
User can view a catalog of products

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/conbini-corner#1]
## 💰 Motivation

If a user visits the site, they should be able to view a catalog of products.

## 📐 Plan

Allow users to view a list of featured products on the landing page.

## 🖼️ Wireframes

<img width="607" alt="landing-page" src="https://github.com/Learning-Fuze/full-stack-project-template/assets/161077888/138805e8-0e35-470a-8ca2-33f2b70d66d9">

## ✅ Task 
- [x] add navbar with the following elements:
  - [x] logo button
  - [x] "Snacks" button, when hovered should display drop down of subcategories: "Chocolate", "Chips", "Candy"
  - [x] "Pantry" button, when hovered should display drop down of subcategories: "Noodles, Condiments, Packaged Foods"
  - [x]  "Drinks" button, when hovered should display drop down of subcategories: "Bottled Drinks", "Canned Drinks"
  - [x] search bar
  - [x] account icon
  - [x] shopping cart icon
- [x] hero section:
  - [x] "Noodles" image card 
  - [x] carousel that shows current deals
  - [x] "Drinks" image card
  - [x] "Candy" image card
- [x] display a list of featured products that include: default image, name of product, price of product, "Add to Cart" button
  - [x] in server.ts create http request that will get the values from the "Products" table in the database if the value in the products "featuredProduct" is true.
