### ISSUE TITLE
User can view details of a single product

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/conbini-corner#3]
## 💰 Motivation

If a user clicks on a product card, they should be able to see details of that product.

## 📐 Plan

Allow users to view a details page of a specific product

## 🖼️ Wireframes

![Product Page](https://github.com/vanessaviray/conbini-corner/assets/161077888/bd5d778e-1a3a-4847-83c6-57791275ca1e)

## ✅ Task 
- [x] when a user clicks on a product card, details of the product should appear:
  - [x] breadcrumbs
  - [x] large image
  - [x] 2 smaller image previews. when clicked should display large image.
  - [x] product subcategory
  - [x] product name
  - [x] price
  - [x] quantity button
  - [x] add to cart button
  - [x] description
