### ISSUE TITLE
User can add a product to their shopping cart

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/conbini-corner#7]
## 💰 Motivation

User should be able to add a product to their shopping cart. The item in the cart should be removable and the user should be able to change the quantity of the item.

## 📐 Plan

Allow users to specify a quantity and add a product to their shopping cart. The badge on the shopping cart should be updated to match the number of items in their cart. In the shopping cart page, it should display a list of products that the user added. When the user clicks on the minus or plus icon, the quantity number and subtotals should reflect the changes. When the quantity is 0, the item should be removed from the cart. When the user clicks remove, the item should be removed from the cart regardless of the quantity number displayed.

## 🖼️ Wireframes

![Checkout Page](https://github.com/vanessaviray/conbini-corner/assets/161077888/377d0212-2fe5-4755-aaa2-324d2140361c)

## ✅ Task 
- [x] track the user's specified quantity:
  - [x] add useState to track quantity
  - [x] when the user clicks the plus icon, increment quantity by 1
  - [x] when the user clicks the minus icon, decrement quantity by 1
  - [x] add useEffect to rerender the quantity on the button
- [x] when the user clicks add to cart:
  - [x] add the product to CartContext.cart array (account for quantity)
  - [x] create HTTP put request to update the quantity in the shoppingCartItems
  - [x] create fetch request to call the http put request
  - [x] add functionality that will update the badge number
- [x] create a component to render each item
