### ISSUE TITLE
User can view a specific category of products

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/conbini-corner#8]
## 💰 Motivation

The user should be able to view a specific category of products.

## 📐 Plan

When the user clicks on a category on the navbar, the user should be directed to a page that shows a list of products with that matching category or subcategory name.

## 🖼️ Wireframes

<img width="607" alt="landing-page" src="https://github.com/Learning-Fuze/full-stack-project-template/assets/161077888/138805e8-0e35-470a-8ca2-33f2b70d66d9">

## ✅ Task 
- [ ] create a new component for the page: "Category.tsx" and create a skeleton layout
- [ ] add route to direct the user to the category page when a category is clicked
- [ ] create an http get request to get the corresponding category data from the database
- [ ] create an async function to send the http request
- [ ] In the desktopNavbar.tsx and mobileNavbar.tsx create an onClick to handle:
  - [ ] getting the name of the category clicked on.. this needs to be passed to the other component somehow
  - [ ] redirects the user to the category page
- [ ] in Category.tsx:
  - [ ] create an async function within a useEffect to call the async function that sends the http request 
  - [ ] map through the results to render the list
- [ ] fix any additional cosmetic styles
